---
title: "Plot eBird Occurrences"
output: html_document
date: "2023-06-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(sf)
library(rgdal)
library(terra)
library(raster)
library(broom)
library(dggridR)
library(rnaturalearth)
library(dplyr)
library(radiant.data)
#devtools::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)
library(viridisLite)
library(viridis) 
```

Might just delete this file from repo, since everything I do here, I also do in cooccur.Rmd (in addition to a bunch of other stuff)

```{r}
#eBird <- readRDS("data_2023/df_nvector_2023.rds")
waxwing <- readRDS("data_2023/effort-merged_data_2023/dat_effort_Bombycilla cedrorum.rds")
#y <- readRDS("data_2023/effort-merged_data_2023/dat_effort_Setophaga coronata.rds")
#y <- y %>% filter(year == 2019)
```

```{r}
waxwing <- waxwing %>% filter(year == 2022)
#waxwing <- waxwing %>% filter(species == "Bombycilla cedrorum")
```


```{r}
#making the returnclass sf, so I can zoom in on it 
state_prov <- rnaturalearth::ne_states(c("united states of america", "canada", "mexico", "honduras", "el salvador", "guatemala", "costa rica"), returnclass = "sf")
state_prov <- st_crop(state_prov, xmin = -160, xmax = -50, ymin = 5, ymax = 75)
```


```{r}
crs(state_prov)
extent(state_prov)
```


```{r}
ggplot() + 
  geom_sf(data=state_prov, colour="grey50", fill="white") + 
  geom_point(data=waxwing, aes(x, y), col="darkorchid4", alpha=.2, size=.1) + 
  theme_bw() + 
  theme_void() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```


```{r}
n = nrow(waxwing)

#weights all together
weight_waxwing <- waxwing %>%
    mutate(day = as.numeric(day),
         year = as.numeric(year)) %>%
group_by(species, year, day) %>%
  summarise(
            numcells = n(), 
            numobs = sum(count),
            #ASK: is should I be dividing count by effort? in movement-ecology-paper.Rmd the var names are count.x and count.y, so I was not sure
            wtmean_lon = weighted.mean(x, count/effort), 
            wtmean_lat = weighted.mean(y, count/effort), 
            wtsd_lon = weighted.sd(x, count/effort),
            wtsd_lat = weighted.sd(y, count/effort) 
            ) %>%
  ungroup()

weight_waxwing <- weight_waxwing %>%
  mutate(DAYm1 = day-1,
         origin = paste0(year, "-01-01"),
         DATE = as.Date(DAYm1, origin=origin), 
         MONTH = month(DATE)) %>%
  mutate(winter = ifelse(MONTH %in% c(10, 11, 12, 1, 2, 3), "winter", "non-winter")) %>%
  arrange(species,DATE) %>%
  ungroup() %>%
  mutate(ID = row_number()) %>%
  dplyr::select(-DAYm1, -origin)

## Calculates the count of observations within each cell, 
#weighted by total eBirder effort on that day in a given cell. 
#Appends into the dataframe as "count_weighted" for analysis. Weighted as the total number of observations of the #target species in a cell divided by the total number of eBirder records in a cell.

#changed resolution to 5 because 6 looked too small on map
dgg <- dgconstruct(project = "FULLER", aperture = 4, topology = "HEXAGON", res = 6)
waxwing$cell <- dgGEO_to_SEQNUM(dgg, waxwing$x, waxwing$y)$seqnum
waxwing$cell_lat <- dgSEQNUM_to_GEO(dgg, waxwing$cell)$lat_deg 
waxwing$cell_lon <- dgSEQNUM_to_GEO(dgg, waxwing$cell)$lon_deg 

#already has frequency column which is count/effort
waxwing <- waxwing %>%
  mutate(count_weighted = count/effort)

spp_counts <- waxwing %>%
  group_by(species, cell) %>% 
  summarise(sum_weighted_count=sum(count_weighted),
            mean_weighted_count=mean(count_weighted),
            sum_count=sum(count))

#Get the grid cell boundaries for cells which had bird observations
grid <- dgcellstogrid(dgg, spp_counts$cell)#, frame=TRUE, wrapcells=TRUE)
#Update the grid cells' properties to include the number of observations in each cell
grid <- merge(grid, spp_counts, by.x="seqnum", by.y="cell")

ggplot() + 
  geom_sf(data=state_prov, colour="grey50", fill="white") + 
  #geom_polygon(data=state_prov, aes(x=long, y=lat, group = group), colour="grey50", fill="white") +
  #geom_polygon(data=countries, aes(x=long, y=lat, group=group), fill=NA, color="black")   +
  geom_sf(data = grid, aes(fill = sum_weighted_count), color = NA) +
  #geom_polygon(data=grid, aes(x=long, y=lat, group=seqnum, fill=mean_weighted_count), size=0.001)    +
  #geom_path   (data=grid, aes(x=long, y=lat, group=seqnum), alpha=0.4, color=NA) +
#  geom_point  (aes(x=cellcenters$lon_deg, y=cellcenters$lat_deg), size=0.5) +
  scale_fill_viridis(option = "D") +
  #scale_fill_gradient(low="gray90", high="darkorchid4") + 
  #scale_fill_gradient2(low="blue", high="red", midpoint = 250) 
  theme_void() + 
  facet_wrap(~species)
```


```{r}
plot(as.data.frame(grid$geometry[[1]][1]))
```





