---
title: "plot migration paths"
author: "Maximilian Wisnefski"
date: '2023-06-16'
output: html_document
---

In this R Markdown, I am plotting the results of Migration-path-window.Rmd for every species

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(viridisLite)
library(viridis)
library(ggpubr)
```


```{r}
dataresult <- readRDS("data_2023/migration_timing_2023.RDS")
latitude <- readRDS("data_2023/daily_mean_lats_2023.RDS")
```


```{r}

species <- unique(latitude$species)
for (s in species){
  df <- latitude[latitude$species == s, ]
  move_dates <- dataresult[dataresult$species == s, ]
  
  print(ggplot(df, aes(x = day, y = lat, color = factor(year))) +
    geom_smooth() +
    ggtitle(s) +
    labs(x = "day of year", y = "weighted mean latitude") +
    scale_colour_viridis(option = "A", discrete = TRUE) +
    #scale_color_continuous(discrete = TRUE) + 
    geom_vline(xintercept = mean(move_dates$spring_beginning),lwd=1,colour="black", linetype = 3) +
    geom_vline(xintercept = mean(move_dates$autumn_beginning),lwd=1,colour="black", linetype = 3) +
    theme(plot.title = element_text(hjust = 0.5)) +
    ylim(10,55))
    
}
```


```{r}
mig_plots <- list()
for (s in species){
  df <- latitude[latitude$species == s, ]
  move_dates <- dataresult[dataresult$species == s, ]
  
  print(
    mig_plot <- ggplot(df, aes(x = day, y = lat, color = factor(year))) +
      geom_smooth() +
      ggtitle(s) +
      labs(x = "day of year", y = "weighted mean latitude") +
      scale_colour_viridis(option = "A", discrete=TRUE) +
      #scale_color_continuous(discrete = TRUE) + 
      #geom_vline(xintercept=0.5,lwd=1,colour="blue") +
      geom_vline(xintercept = mean(move_dates$spring_beginning),lwd=1,colour="black", linetype = 3) +
      geom_vline(xintercept = mean(move_dates$autumn_beginning),lwd=1,colour="black", linetype = 3) +
      geom_vline(xintercept = mean(move_dates$spring_end),lwd=1,colour="black", linetype = 3) +
      geom_vline(xintercept = mean(move_dates$autumn_end),lwd=1,colour="black", linetype = 3) +
      theme_bw() +
      labs(color = "year") +
      theme(plot.title = element_text(hjust = 0.5))
    )
  mig_plots <- append(mig_plots, list(mig_plot))
  #ggsave(paste0("figs/",s,"_migration_path.png"))
}
```





```{r}
#trying to find nice way to arrange plots with ggarrange
ggarrange(mig_plots[1][[1]], mig_plots[3][[1]], mig_plots[6][[1]], mig_plots[7][[1]],
          mig_plots[8][[1]], mig_plots[10][[1]], mig_plots[13][[1]], mig_plots[15][[1]], 
          common.legend = TRUE, legend = "right")

#ggsave("../test_ggarrange.png", bg = "transparent", height = 10, width = 10)
```


```{r}
#finding average migration start/end dates for each species
mig_dates <- dataresult %>% group_by(species) %>%
  summarise(avg_spr_beginning = mean(spring_beginning),
            avg_spr_middle = mean(spring_middle),
            avg_spr_end = mean(spring_end),
            avg_aut_beginning = mean(autumn_beginning),
            avg_aut_middle = mean(autumn_middle),
            avg_aut_end = mean(autumn_end))
```



