---
title: "Waxwings"
author: "Sarah Supp"
date: "10/25/2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggmap)
library(maptools)
library(fields)
library(sp)
library(raster)
library(maps)
library(mapdata)
library(usmap)
library(rgdal)
library(gamm4)
library(sf)
library(ggfortify)
library(lubridate)
library(ggplot2)
library(adehabitatHR)
library(dggridR)

waxwings <- read_tsv("data/ebd_cedwax_200708_201810_relAug-2018.txt")
robins <- read_tsv("data/ebd_amerob_200708_201810_relAug-2018.txt")
bluebirds <-read_tsv("data/ebd_easblu_200708_201810_relAug-2018.txt")
warblers <- read_tsv("data/ebd_yerwar_200708_201810_relAug-2018.txt")
mockers <- read_tsv("data/ebd_normoc_200708_201810_relAug-2018.txt")

```

Create columns for year, month, day, and julian day
```{r}

waxwings <- waxwings %>%
  mutate(year = format(as.POSIXct(`OBSERVATION DATE`), "%Y"), 
         month = format(as.POSIXct(`OBSERVATION DATE`), "%m"),
         day = format(as.POSIXct(`OBSERVATION DATE`), "%d"),
         julian = yday(format(as.POSIXct(`OBSERVATION DATE`, "%Y/%m/%d")))) %>%
  mutate(months = recode(month, "01" = "January", "02" = "February", "03" = "March", "04" = "April",
                         "05"="May", "06"="June", "07"="July", "08"="August", "09"="September",
                         "10"="October", "11"="November", "12"="December")) %>%
  mutate(months = ordered(months, levels = c("October", "November", "December", "January", "February",
                                             "March", "April", "May", "June", "July", "August", "Sep")))

robins <- robins %>%
  mutate(year = format(as.POSIXct(`OBSERVATION DATE`), "%Y"), 
         month = format(as.POSIXct(`OBSERVATION DATE`), "%m"),
         day = format(as.POSIXct(`OBSERVATION DATE`), "%d"),
         julian = yday(format(as.POSIXct(`OBSERVATION DATE`, "%Y/%m/%d")))) %>%
  mutate(months = recode(month, "01" = "January", "02" = "February", "03" = "March", "04" = "April",
                         "05"="May", "06"="June", "07"="July", "08"="August", "09"="September",
                         "10"="October", "11"="November", "12"="December")) %>%
  mutate(months = ordered(months, levels = c("October", "November", "December", "January", "February",
                                             "March", "April", "May", "June", "July", "August", "Sep")))

```


Filter data to just the most recent years for preliminary graphics.
```{r}

cewa_1617 <- waxwings %>%
  filter(year %in% c(2016, 2017))

amro_1617 <- robins %>%
  filter(year %in% c(2016, 2017))

write_csv(cewa_1617, "data/cewa_1617.csv")
write_csv(amro_1617, "data/amro_1617.csv")
```


# plot the 2016-2017 winter data for WAXWINGS and ROBINS onto a map of the eastern US and Great Plains
```{r}

#get map for states of interest
all_states <- map_data("state")
states <- subset(all_states, region %in% c('ohio', 'michigan', 'kentucky', 'tennessee', 'indiana', 
                                           'illinois', 'iowa', 'nebraska','south dakota', 'north dakota',
                                           'minnesota', 'wisconsin', 'missouri', 'kansas'))

cewa_1617winter <- waxwings %>%
  filter(year==2016 & month %in% c("11", "12") | year == 2017 & month %in% c("01", "02", "03")) %>%
  filter(STATE %in% c("Ohio", "Michigan", "Kentucky", "Tennessee", "Indiana", "Illinois", "Iowa", "Nebraska",
                      "South Dakota", "North Dakota", "Minnesota", "Wisconsin", "Missouri", "Kansas")) %>%
  filter(months %in% c("November", "December","January", "February", "March"))

amro_1617winter <- robins %>%
  filter(year==2016 & month %in% c("11", "12") | year == 2017 & month %in% c("01", "02", "03")) %>%
  filter(STATE %in% c("Ohio", "Michigan", "Kentucky", "Tennessee", "Indiana", "Illinois", "Iowa", "Nebraska",
                      "South Dakota", "North Dakota", "Minnesota", "Wisconsin", "Missouri", "Kansas")) %>%
  filter(months %in% c("November", "December","January", "February", "March"))


# plot winter waxwings only
#TODO: add points for known cedar patches, repeat for robins?
p <- ggplot() +
  geom_polygon( data=states, aes(x=long, y=lat, group = group), colour="black", fill="white" ) +
  geom_point(data=cewa_1617winter, aes(x=LONGITUDE, y=LATITUDE), alpha=0.25, size=0.5, col="mediumpurple") +
  facet_wrap(~months, nrow=1) + 
  labs(title="Cedar Waxwing locations in winter 2016-2017") + 
  theme_bw() + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p

#plot winter robins only
p <- ggplot() +
  geom_polygon( data=states, aes(x=long, y=lat, group = group), colour="black", fill="white" ) +
  geom_point(data=amro_1617winter, aes(x=LONGITUDE, y=LATITUDE), alpha=0.25, size=0.5, col="indianred") +
  facet_wrap(~months) + 
  labs(title="American Robin locations in winter 2016-2017") + 
  theme_bw() + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p

#plot winter robins and waxwings together
p <- ggplot() +
  geom_polygon( data=states, aes(x=long, y=lat, group = group), colour="black", fill="white" ) +
  geom_point(data=amro_1617winter, aes(x=LONGITUDE, y=LATITUDE), alpha=0.25, size=0.5, col="indianred") +
  geom_point(data=cewa_1617winter, aes(x=LONGITUDE, y=LATITUDE), alpha=0.25, size=0.5, col="mediumpurple") +
  facet_wrap(~months) + 
  labs(title="American Robin locations in winter 2016-2017") + 
  theme_bw() + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p

```

Plot icosahedron cells onto map
```{r}
#Construct a global grid with cells approximately 1000 miles across
dggs <- dgconstruct(res=12, resround='down')

#Get the corresponding grid cells for each earthquake epicenter (lat-long pair)
cewa_1617winter$cell <- dgGEO_to_SEQNUM(dggs, cewa_1617winter$LONGITUDE, cewa_1617winter$LATITUDE)$seqnum

#Converting SEQNUM to GEO gives the center coordinates of the cells
cellcenters <- dgSEQNUM_to_GEO(dggs,cewa_1617winter$cell)

#Get the number of earthquakes in each cell
birdcounts <- cewa_1617winter %>% 
  group_by(cell) %>% 
  summarise(count=n())

#Get the grid cell boundaries for cells which had birds
grid <- dgcellstogrid(dggs, birdcounts$cell, frame=TRUE, wrapcells=TRUE)

#Update the grid cells' properties to include the number of occurrences in each cell
grid <- merge(grid, birdcounts, by.x="cell", by.y="cell")
# 
# #Make adjustments so the output is more visually interesting
 grid$count <- log(grid$count)
# cutoff <- quantile(grid$count, 0.9)
# grid <- grid %>% mutate(count=ifelse(count>cutoff,cutoff,count))

#Plot everything on a flat map
p<- ggplot() + 
    geom_polygon(data=states, aes(x=long, y=lat, group=group), fill="white", color="black")   +
    geom_polygon(data=grid,      aes(x=long, y=lat, group=group, fill=count), alpha=0.4)    +
    geom_path   (data=grid,      aes(x=long, y=lat, group=group, col=count), alpha=0.4) +
    #geom_point  (aes(x=cellcenters$lon_deg, y=cellcenters$lat_deg)) +
    scale_fill_gradient(low="yellow", high="darkorchid") + 
    scale_color_gradient(low="yellow", high="darkorchid")
p


```

